create table mail_response(
  id bigserial not null primary key,
  content_type VARCHAR ,
  message_id VARCHAR ,
  mime_version VARCHAR,
  mail_to VARCHAR ,
  x_envelope_from VARCHAR ,
  x_mailgun_incoming VARCHAR ,
  x_originating_ip VARCHAR ,
  body_html VARCHAR ,
  body_plain text,
  domain VARCHAR ,
  mail_from VARCHAR ,
  message_headers VARCHAR ,
  message_url VARCHAR ,
  recipient VARCHAR ,
  sender VARCHAR ,
  signature VARCHAR ,
  stripped_html VARCHAR ,
  stripped_signature VARCHAR ,
  stripped_text text ,
  subject VARCHAR,
  time TIMESTAMP ,
  token VARCHAR ,
  is_used boolean,
  in_reply_to VARCHAR ,
  created_on timestamp not null default current_timestamp,
  modified_on timestamp not null default current_timestamp
);